spring:
  ai:
    azure:
      openai:
        chat:
          options:
            deployment-name: "${AZURE_OPENAI_DEPLOYMENT_NAME}"
        endpoint: "${AZURE_OPENAI_ENDPOINT}"
  cloud:
    azure:
      credential:
        client-id: "${AZURE_CLIENT_ID}"
        client-secret: "${AZURE_CLIENT_SECRET}"
      profile:
        tenant-id: "${AZURE_TENANT_ID}"
